# Hmm, better with image or without image?  Seems fine here without, and if
# not running a custom image what's the point?
name: Go/Pg Demo CI
on: push

jobs:
  test-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.1'

      - name: Run tests
        run: go test ./...
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          report: 'true'
          chart: 'true'
          amend: 'false'
